apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hxb-sdk-docs
    component: microservice
  name: hxb-sdk-docs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hxb-sdk-docs
      component: microservice
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hxb-sdk-docs
        component: microservice
      name: hxb-sdk-docs
    spec:
      containers:
      - env:
        - name: ENV
          value: production
        image: beee/hxb-sdk-docs:b4b4fc1ebfe04104b393b25b11bebac094545108
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "20"
        name: beee-hxb-sdk-docs
        ports:
        - containerPort: 80
          name: hxb-sdk-docs
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: hxb-sdk-docs
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 60m
            memory: 64Mi
      dnsPolicy: ClusterFirst
      nodeSelector:
        eks.amazonaws.com/nodegroup: nodepoolhx-spot
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 1800
