apiVersion: v1
kind: Service
metadata:
  name: beee-hxb-sdk-docs
  labels:
    app: hxb-sdk-docs
    component: microservice
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hxb-sdk-docs
  sessionAffinity: None
  type: ClusterIP