apiVersion: v1
kind: Service
metadata:
  labels:
    app: hxb-sdk-docs
    component: microservice
  name: beee-hxb-sdk-docs
  namespace: default
spec:
  ports:
  - name: web
    port: 80
  selector:
    app: hxb-sdk-docs
